name: Tag and Release
on:
  workflow_dispatch:

env:
  FINAL_PACKAGE_NAME: statement-verifier-chrome-mv3.zip

jobs:
  zip-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node globally
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install yarn globally
        run: npm install --global yarn

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Install dependencies
        run: yarn install

      - name: Display version
        run: cat package.json | jq ".version"
