name: Tag and Release
run-name: Tag and Release
on:
  workflow_dispatch:
    inputs:
      yarn-version-options:
        required: true
        type: choice
        description: Yarn Version bump options
        options:
          - --patch
          - --minor
          - --major

permissions:
  contents: write

env:
  BUILD_DIST_NAME: chrome-mv3-prod
  FINAL_DIST_NAME: statement-verifier-chrome-mv3
  CURRENT_TAG: ""

jobs:
  zip-extension:
    runs-on: ubuntu-latest
    environment: tag and release

    steps:

      - name: Setup node globally
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Build and Package
        run: yarn build && yarn package

      - name: Bump Version & push to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@no-reply.com
          yarn version ${{ github.event.inputs.yarn-version-options }}
          git push -u origin main
          echo "CURRENT_TAG=v$(cat package.json | jq .version | tr -d '\"')" >> $GITHUB_ENV

      - name: Prep Artifacts
        run: |
          mv build/${{ env.BUILD_DIST_NAME }}.zip build/${{ env.FINAL_DIST_NAME }}-${{ env.CURRENT_TAG }}.zip
          

      - name: Save Artifact(s)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FINAL_DIST_NAME }}-${{ env.CURRENT_TAG }}.zip
          path: build/**.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.CURRENT_TAG }}
          files: build/${{ env.FINAL_DIST_NAME }}-${{ env.CURRENT_TAG }}.zip
          prerelease: true
          body: |
            [Installation instructions](https://github.com/M-Dutta/statement-verifier/blob/main/README.md#loading-the-extension)
            
            **Changelog**: https://github.com/M-Dutta/statement-verifier/commits/${{ env.CURRENT_TAG }}
