name: Tag and Release
on:
  workflow_dispatch:
    inputs:
      yarn-version-options:
        required: true
        type: choice
        description: Yarn Version bump options
        options:
        - --major
        - --minor
        - --patch

permissions:
    contents: write

env:
  FINAL_PACKAGE_NAME: statement-verifier-chrome-mv3.zip

jobs:
  zip-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node globally
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install yarn globally
        run: npm install --global yarn

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Current version
        run: cat package.json | jq ".version"

      - name: Bump Version, push to main
        run: |
          yarn version ${{ github.event.inputs.yarn-version-options }}
          git push -u origin main
          git push origin tag $(cat package.json | jq ".version")
