name: Tag and Release
run-name: Tag and Release
on:
  workflow_dispatch:
    inputs:
      yarn-version-options:
        required: true
        type: choice
        description: Yarn Version bump options
        options:
          - --patch
          - --minor
          - --major

permissions:
  contents: write

env:
  FINAL_PACKAGE_NAME: statement-verifier-chrome-mv3.zip

jobs:
  zip-extension:
    runs-on: ubuntu-latest
    environment: tag and release

    steps:

      - name: Setup node globally
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install yarn globally
        run: npm install --global yarn

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install dependencies
        run: yarn install

      - name: Install package
        run: yarn build && yarn package

      - name: Current version
        run: cat package.json | jq ".version" | tr -d '"'

      - name: Bump Version, push to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@no-reply.com
          yarn version ${{ github.event.inputs.yarn-version-options }}
          git push -u origin main

      - name: Show New Tag(s)
        run: echo v$(cat package.json | jq ".version" | tr -d '"')

      - name: Push New Tag
        run: |  
          git push -u origin tag v$(cat package.json | jq ".version" | tr -d '"')

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-mv3-prod.zip
          path: build/chrome-mv3-prod.zip

